format = """
[](fg:#454c5c bg:#454c5c)\
$directory\
${custom.directory_arrow_without_git}\
${custom.directory_arrow_with_clean_branch}\
${custom.directory_arrow_with_dirty_branch}\
${custom.git_branch_clean_leading_space}\
${custom.git_branch_clean}\
${custom.git_branch_dirty_leading_space}\
${custom.git_branch_dirty}\
${custom.clean_branch_final_arrow}\
${custom.dirty_branch_final_arrow}\
$cmd_duration \
"""

add_newline = false

[line_break]
disabled = true

[directory]
style = 'bg:#454c5c'
format = '[ $path ]($style)'
truncation_length = 8
truncation_symbol = '…/'

[custom.directory_arrow_without_git]
when = '[[ "$(git rev-parse --is-inside-work-tree 2>/dev/null)" != "true" ]]'
format = '[](fg:#454c5c)'

[custom.directory_arrow_with_clean_branch]
when = '[[ -z "$(git status --porcelain)" && -d .git ]]'
format = '[](fg:#454c5c bg:#a8bd91)'

[custom.directory_arrow_with_dirty_branch]
when = '[[ -n "$(git status --porcelain)" ]]'
format = '[](fg:#454c5c bg:#bf616a)'

[custom.git_branch_clean_leading_space]
when = '[[ -z "$(git status --porcelain)" && -d .git ]]'
format = '[ ](bg:#a8bd91)'

[custom.git_branch_dirty_leading_space]
when = '[[ -n "$(git status --porcelain)" ]]'
format = '[ ](bg:#bf616a)'

[custom.git_branch_clean]
when = '[[ -z "$(git status --porcelain)" && -d .git ]]'
command = "echo \" $(git symbolic-ref --short HEAD)\""
style = 'bg:#a8bd91 fg:#000000'

[custom.git_branch_dirty]
when = '[[ -n "$(git status --porcelain)" ]]'
command = "echo \" $(git symbolic-ref --short HEAD)\""
style = 'bg:#bf616a fg:#000000'

[custom.clean_branch_final_arrow]
when = '[[ -z "$(git status --porcelain)" && -d .git ]]'
format = '[](fg:#a8bd91)'

[custom.dirty_branch_final_arrow]
when = '[[ -n "$(git status --porcelain)" ]]'
format = '[](fg:#bf616a)'

[cmd_duration]
min_time = 500
format = ' [$duration](#8fbcbb)'
